CREATE TABLE `appointments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`facility_id` integer NOT NULL,
	`dock_door_id` integer NOT NULL,
	`appointment_type` text NOT NULL,
	`scheduled_date` text NOT NULL,
	`scheduled_time` text NOT NULL,
	`duration_minutes` integer DEFAULT 60 NOT NULL,
	`end_time` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`carrier_id` integer,
	`carrier_name` text,
	`driver_name` text,
	`truck_number` text,
	`trailer_number` text,
	`driver_phone` text,
	`load_ref` text,
	`po_number` text,
	`commodity` text,
	`special_instructions` text,
	`checked_in_at` text,
	`in_progress_at` text,
	`completed_at` text,
	`cancelled_at` text,
	`cancellation_reason` text,
	`wait_minutes` real,
	`dock_minutes` real,
	`total_dwell_minutes` real,
	`notes` text,
	`created_by` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`facility_id`) REFERENCES `facilities`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`dock_door_id`) REFERENCES `dock_doors`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dock_doors` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`facility_id` integer NOT NULL,
	`name` text NOT NULL,
	`door_type` text NOT NULL,
	`operating_hours_start` text,
	`operating_hours_end` text,
	`status` text DEFAULT 'active' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`facility_id`) REFERENCES `facilities`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `facilities` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`address_street` text NOT NULL,
	`address_city` text NOT NULL,
	`address_state` text NOT NULL,
	`address_zip` text NOT NULL,
	`operating_hours_start` text DEFAULT '06:00' NOT NULL,
	`operating_hours_end` text DEFAULT '18:00' NOT NULL,
	`timezone` text DEFAULT 'America/Chicago' NOT NULL,
	`buffer_minutes` integer DEFAULT 30 NOT NULL,
	`notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
