CREATE TABLE `check_calls` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`load_id` integer NOT NULL,
	`status` text NOT NULL,
	`location_city` text,
	`location_state` text,
	`eta` text,
	`notes` text,
	`contact_method` text DEFAULT 'phone',
	`called_by` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`load_id`) REFERENCES `loads`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `load_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`customer_id` integer,
	`customer_name` text,
	`origin_city` text,
	`origin_state` text,
	`dest_city` text,
	`dest_state` text,
	`equipment_type` text DEFAULT 'dry_van',
	`weight` integer,
	`commodity` text,
	`customer_rate` real,
	`special_instructions` text,
	`use_count` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `loads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`load_number` text NOT NULL,
	`customer_id` integer,
	`customer_name` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`origin_city` text NOT NULL,
	`origin_state` text NOT NULL,
	`origin_zip` text,
	`origin_address` text,
	`origin_contact_name` text,
	`origin_contact_phone` text,
	`pickup_date` text,
	`pickup_time_from` text,
	`pickup_time_to` text,
	`pickup_number` text,
	`dest_city` text NOT NULL,
	`dest_state` text NOT NULL,
	`dest_zip` text,
	`dest_address` text,
	`dest_contact_name` text,
	`dest_contact_phone` text,
	`delivery_date` text,
	`delivery_time_from` text,
	`delivery_time_to` text,
	`delivery_number` text,
	`equipment_type` text DEFAULT 'dry_van' NOT NULL,
	`weight` integer,
	`commodity` text,
	`temperature_min` real,
	`temperature_max` real,
	`dims_length` real,
	`dims_width` real,
	`dims_height` real,
	`special_instructions` text,
	`carrier_id` integer,
	`carrier_name` text,
	`carrier_contact` text,
	`carrier_phone` text,
	`carrier_email` text,
	`customer_rate` real,
	`carrier_rate` real,
	`margin` real,
	`margin_pct` real,
	`rate_type` text DEFAULT 'flat',
	`miles` integer,
	`customer_ref` text,
	`bol_number` text,
	`pro_number` text,
	`posted_at` text,
	`covered_at` text,
	`dispatched_at` text,
	`picked_up_at` text,
	`delivered_at` text,
	`invoiced_at` text,
	`closed_at` text,
	`cancelled_at` text,
	`cancellation_reason` text,
	`notes` text,
	`tags` text,
	`created_by` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `loads_load_number_unique` ON `loads` (`load_number`);